id: P009117
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN8170
  title: གནས་མཆོག་བོན་རི་ཆེན་མོའི་དཀར་ཆག་རབ་གསལ་ཉི་མ་གཞོན་ནུའི་འོད།
  author: ''
  volumes:
    8114e1a5bdbb44fa8f7108631e01449d:
      image_group_id: I3CN8172
      title: ''
      volume_number: 1
      total_pages: 330
